// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: zephyr_auth.proto

package server

import (
	"context"

	"zephyr-go/app/auth/internal/logic"
	"zephyr-go/app/auth/internal/svc"
	"zephyr-go/app/auth/pb/pb"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

// 【账号密码登录】
func (s *AuthServiceServer) LoginVerify(ctx context.Context, in *pb.LoginVerifyReq) (*pb.LoginVerifyResp, error) {
	l := logic.NewLoginVerifyLogic(ctx, s.svcCtx)
	return l.LoginVerify(in)
}

// 【Token刷新】
func (s *AuthServiceServer) RefreshToken(ctx context.Context, in *pb.RefreshTokenReq) (*pb.LoginVerifyResp, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

// 【安全登出】
func (s *AuthServiceServer) Logout(ctx context.Context, in *pb.LogoutReq) (*pb.EmptyResp, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}
