services:
  # ---------------- Microservices ---------------- #
  identity:
    image: zephyr-identity:latest
    build:
      context: .
      dockerfile: app/identity/Dockerfile
    container_name: zephyr-identity
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8081:8081"
    volumes:
      - /app/logs/identity:/app/logs/identity
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"

  auth:
    image: zephyr-auth:latest
    build:
      context: .
      dockerfile: app/auth/Dockerfile
    container_name: zephyr-auth
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8080:8080"
    depends_on:
      - identity
    volumes:
      - /app/logs/auth:/app/logs/auth
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"

  gateway:
    image: zephyr-gateway:latest
    build:
      context: .
      dockerfile: app/gateway/Dockerfile
    container_name: zephyr-gateway
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8888:8888"
    depends_on:
      - auth
      - identity
    volumes:
      - /app/logs/gateway:/app/logs/gateway
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"

networks:
  default:
    name: infra_default
    external: true
