// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: zephyr_auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginVerifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	TenantCode    string                 `protobuf:"bytes,3,opt,name=tenant_code,json=tenantCode,proto3" json:"tenant_code,omitempty"`
	CaptchaCode   string                 `protobuf:"bytes,4,opt,name=captcha_code,json=captchaCode,proto3" json:"captcha_code,omitempty"` // 预留图形验证码
	CaptchaUuid   string                 `protobuf:"bytes,5,opt,name=captcha_uuid,json=captchaUuid,proto3" json:"captcha_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginVerifyReq) Reset() {
	*x = LoginVerifyReq{}
	mi := &file_zephyr_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginVerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginVerifyReq) ProtoMessage() {}

func (x *LoginVerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_zephyr_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginVerifyReq.ProtoReflect.Descriptor instead.
func (*LoginVerifyReq) Descriptor() ([]byte, []int) {
	return file_zephyr_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginVerifyReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginVerifyReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginVerifyReq) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *LoginVerifyReq) GetCaptchaCode() string {
	if x != nil {
		return x.CaptchaCode
	}
	return ""
}

func (x *LoginVerifyReq) GetCaptchaUuid() string {
	if x != nil {
		return x.CaptchaUuid
	}
	return ""
}

type LoginVerifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Expire        int64                  `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
	UserCode      string                 `protobuf:"bytes,4,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	TenantCode    string                 `protobuf:"bytes,5,opt,name=tenant_code,json=tenantCode,proto3" json:"tenant_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginVerifyResp) Reset() {
	*x = LoginVerifyResp{}
	mi := &file_zephyr_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginVerifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginVerifyResp) ProtoMessage() {}

func (x *LoginVerifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_zephyr_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginVerifyResp.ProtoReflect.Descriptor instead.
func (*LoginVerifyResp) Descriptor() ([]byte, []int) {
	return file_zephyr_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginVerifyResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginVerifyResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginVerifyResp) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *LoginVerifyResp) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *LoginVerifyResp) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

type RefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	mi := &file_zephyr_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_zephyr_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_zephyr_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessTokenJti  string                 `protobuf:"bytes,1,opt,name=access_token_jti,json=accessTokenJti,proto3" json:"access_token_jti,omitempty"`
	RefreshTokenJti string                 `protobuf:"bytes,2,opt,name=refresh_token_jti,json=refreshTokenJti,proto3" json:"refresh_token_jti,omitempty"`
	AccessExpire    int64                  `protobuf:"varint,3,opt,name=access_expire,json=accessExpire,proto3" json:"access_expire,omitempty"` // 用于设置黑名单过期时间
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_zephyr_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_zephyr_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_zephyr_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutReq) GetAccessTokenJti() string {
	if x != nil {
		return x.AccessTokenJti
	}
	return ""
}

func (x *LogoutReq) GetRefreshTokenJti() string {
	if x != nil {
		return x.RefreshTokenJti
	}
	return ""
}

func (x *LogoutReq) GetAccessExpire() int64 {
	if x != nil {
		return x.AccessExpire
	}
	return 0
}

type EmptyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResp) Reset() {
	*x = EmptyResp{}
	mi := &file_zephyr_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResp) ProtoMessage() {}

func (x *EmptyResp) ProtoReflect() protoreflect.Message {
	mi := &file_zephyr_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResp.ProtoReflect.Descriptor instead.
func (*EmptyResp) Descriptor() ([]byte, []int) {
	return file_zephyr_auth_proto_rawDescGZIP(), []int{4}
}

var File_zephyr_auth_proto protoreflect.FileDescriptor

const file_zephyr_auth_proto_rawDesc = "" +
	"\n" +
	"\x11zephyr_auth.proto\x12\x04auth\"\xaf\x01\n" +
	"\x0eLoginVerifyReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vtenant_code\x18\x03 \x01(\tR\n" +
	"tenantCode\x12!\n" +
	"\fcaptcha_code\x18\x04 \x01(\tR\vcaptchaCode\x12!\n" +
	"\fcaptcha_uuid\x18\x05 \x01(\tR\vcaptchaUuid\"\xaf\x01\n" +
	"\x0fLoginVerifyResp\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x16\n" +
	"\x06expire\x18\x03 \x01(\x03R\x06expire\x12\x1b\n" +
	"\tuser_code\x18\x04 \x01(\tR\buserCode\x12\x1f\n" +
	"\vtenant_code\x18\x05 \x01(\tR\n" +
	"tenantCode\"6\n" +
	"\x0fRefreshTokenReq\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x86\x01\n" +
	"\tLogoutReq\x12(\n" +
	"\x10access_token_jti\x18\x01 \x01(\tR\x0eaccessTokenJti\x12*\n" +
	"\x11refresh_token_jti\x18\x02 \x01(\tR\x0frefreshTokenJti\x12#\n" +
	"\raccess_expire\x18\x03 \x01(\x03R\faccessExpire\"\v\n" +
	"\tEmptyResp2\xb3\x01\n" +
	"\vAuthService\x12:\n" +
	"\vLoginVerify\x12\x14.auth.LoginVerifyReq\x1a\x15.auth.LoginVerifyResp\x12<\n" +
	"\fRefreshToken\x12\x15.auth.RefreshTokenReq\x1a\x15.auth.LoginVerifyResp\x12*\n" +
	"\x06Logout\x12\x0f.auth.LogoutReq\x1a\x0f.auth.EmptyRespB\x06Z\x04./pbb\x06proto3"

var (
	file_zephyr_auth_proto_rawDescOnce sync.Once
	file_zephyr_auth_proto_rawDescData []byte
)

func file_zephyr_auth_proto_rawDescGZIP() []byte {
	file_zephyr_auth_proto_rawDescOnce.Do(func() {
		file_zephyr_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zephyr_auth_proto_rawDesc), len(file_zephyr_auth_proto_rawDesc)))
	})
	return file_zephyr_auth_proto_rawDescData
}

var file_zephyr_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_zephyr_auth_proto_goTypes = []any{
	(*LoginVerifyReq)(nil),  // 0: auth.LoginVerifyReq
	(*LoginVerifyResp)(nil), // 1: auth.LoginVerifyResp
	(*RefreshTokenReq)(nil), // 2: auth.RefreshTokenReq
	(*LogoutReq)(nil),       // 3: auth.LogoutReq
	(*EmptyResp)(nil),       // 4: auth.EmptyResp
}
var file_zephyr_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.LoginVerify:input_type -> auth.LoginVerifyReq
	2, // 1: auth.AuthService.RefreshToken:input_type -> auth.RefreshTokenReq
	3, // 2: auth.AuthService.Logout:input_type -> auth.LogoutReq
	1, // 3: auth.AuthService.LoginVerify:output_type -> auth.LoginVerifyResp
	1, // 4: auth.AuthService.RefreshToken:output_type -> auth.LoginVerifyResp
	4, // 5: auth.AuthService.Logout:output_type -> auth.EmptyResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zephyr_auth_proto_init() }
func file_zephyr_auth_proto_init() {
	if File_zephyr_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zephyr_auth_proto_rawDesc), len(file_zephyr_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zephyr_auth_proto_goTypes,
		DependencyIndexes: file_zephyr_auth_proto_depIdxs,
		MessageInfos:      file_zephyr_auth_proto_msgTypes,
	}.Build()
	File_zephyr_auth_proto = out.File
	file_zephyr_auth_proto_goTypes = nil
	file_zephyr_auth_proto_depIdxs = nil
}
