// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: zephyr_auth.proto

package authservice

import (
	"context"

	"zephyr-go/app/auth/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EmptyResp       = pb.EmptyResp
	LoginVerifyReq  = pb.LoginVerifyReq
	LoginVerifyResp = pb.LoginVerifyResp
	LogoutReq       = pb.LogoutReq
	RefreshTokenReq = pb.RefreshTokenReq

	AuthService interface {
		// 【账号密码登录】
		LoginVerify(ctx context.Context, in *LoginVerifyReq, opts ...grpc.CallOption) (*LoginVerifyResp, error)
		// 【Token刷新】
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*LoginVerifyResp, error)
		// 【安全登出】
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*EmptyResp, error)
	}

	defaultAuthService struct {
		cli zrpc.Client
	}
)

func NewAuthService(cli zrpc.Client) AuthService {
	return &defaultAuthService{
		cli: cli,
	}
}

// 【账号密码登录】
func (m *defaultAuthService) LoginVerify(ctx context.Context, in *LoginVerifyReq, opts ...grpc.CallOption) (*LoginVerifyResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.LoginVerify(ctx, in, opts...)
}

// 【Token刷新】
func (m *defaultAuthService) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*LoginVerifyResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

// 【安全登出】
func (m *defaultAuthService) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewAuthServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}
