// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: identity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Base ---
type EmptyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	mi := &file_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{0}
}

type SuccessResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessResp) Reset() {
	*x = SuccessResp{}
	mi := &file_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResp) ProtoMessage() {}

func (x *SuccessResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResp.ProtoReflect.Descriptor instead.
func (*SuccessResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{1}
}

func (x *SuccessResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- Auth & Current User ---
type GetUserAuthInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	TenantCode    string                 `protobuf:"bytes,2,opt,name=tenant_code,json=tenantCode,proto3" json:"tenant_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAuthInfoReq) Reset() {
	*x = GetUserAuthInfoReq{}
	mi := &file_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAuthInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAuthInfoReq) ProtoMessage() {}

func (x *GetUserAuthInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAuthInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserAuthInfoReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserAuthInfoReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserAuthInfoReq) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

type GetUserAuthInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCode      string                 `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	TenantCode    string                 `protobuf:"bytes,3,opt,name=tenant_code,json=tenantCode,proto3" json:"tenant_code,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAuthInfoResp) Reset() {
	*x = GetUserAuthInfoResp{}
	mi := &file_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAuthInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAuthInfoResp) ProtoMessage() {}

func (x *GetUserAuthInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAuthInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserAuthInfoResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserAuthInfoResp) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *GetUserAuthInfoResp) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *GetUserAuthInfoResp) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *GetUserAuthInfoResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCode      string                 `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	TenantCode    string                 `protobuf:"bytes,2,opt,name=tenant_code,json=tenantCode,proto3" json:"tenant_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserInfoReq) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *GetUserInfoReq) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

type UserEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCode      string                 `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEntity) Reset() {
	*x = UserEntity{}
	mi := &file_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEntity) ProtoMessage() {}

func (x *UserEntity) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEntity.ProtoReflect.Descriptor instead.
func (*UserEntity) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{5}
}

func (x *UserEntity) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *UserEntity) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserEntity) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserEntity            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Perms         []string               `protobuf:"bytes,3,rep,name=perms,proto3" json:"perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserInfoResp) GetUser() *UserEntity {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserInfoResp) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetUserInfoResp) GetPerms() []string {
	if x != nil {
		return x.Perms
	}
	return nil
}

// --- Dept ---
type DeptDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	ParentCode    string                 `protobuf:"bytes,3,opt,name=parent_code,json=parentCode,proto3" json:"parent_code,omitempty"`
	Leaf          int32                  `protobuf:"varint,4,opt,name=leaf,proto3" json:"leaf,omitempty"`
	DeptName      string                 `protobuf:"bytes,5,opt,name=dept_name,json=deptName,proto3" json:"dept_name,omitempty"`
	OrderNum      int32                  `protobuf:"varint,6,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    string                 `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Children      []*DeptDetail          `protobuf:"bytes,9,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptDetail) Reset() {
	*x = DeptDetail{}
	mi := &file_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptDetail) ProtoMessage() {}

func (x *DeptDetail) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptDetail.ProtoReflect.Descriptor instead.
func (*DeptDetail) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{7}
}

func (x *DeptDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeptDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeptDetail) GetParentCode() string {
	if x != nil {
		return x.ParentCode
	}
	return ""
}

func (x *DeptDetail) GetLeaf() int32 {
	if x != nil {
		return x.Leaf
	}
	return 0
}

func (x *DeptDetail) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *DeptDetail) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *DeptDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeptDetail) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *DeptDetail) GetChildren() []*DeptDetail {
	if x != nil {
		return x.Children
	}
	return nil
}

type DeptTreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*DeptDetail          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptTreeResp) Reset() {
	*x = DeptTreeResp{}
	mi := &file_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptTreeResp) ProtoMessage() {}

func (x *DeptTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptTreeResp.ProtoReflect.Descriptor instead.
func (*DeptTreeResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{8}
}

func (x *DeptTreeResp) GetList() []*DeptDetail {
	if x != nil {
		return x.List
	}
	return nil
}

type DeptSaveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ParentCode    string                 `protobuf:"bytes,2,opt,name=parent_code,json=parentCode,proto3" json:"parent_code,omitempty"`
	DeptName      string                 `protobuf:"bytes,3,opt,name=dept_name,json=deptName,proto3" json:"dept_name,omitempty"`
	OrderNum      int32                  `protobuf:"varint,4,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptSaveReq) Reset() {
	*x = DeptSaveReq{}
	mi := &file_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptSaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptSaveReq) ProtoMessage() {}

func (x *DeptSaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptSaveReq.ProtoReflect.Descriptor instead.
func (*DeptSaveReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{9}
}

func (x *DeptSaveReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeptSaveReq) GetParentCode() string {
	if x != nil {
		return x.ParentCode
	}
	return ""
}

func (x *DeptSaveReq) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *DeptSaveReq) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *DeptSaveReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeptUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	ParentCode    string                 `protobuf:"bytes,3,opt,name=parent_code,json=parentCode,proto3" json:"parent_code,omitempty"`
	DeptName      string                 `protobuf:"bytes,4,opt,name=dept_name,json=deptName,proto3" json:"dept_name,omitempty"`
	OrderNum      int32                  `protobuf:"varint,5,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptUpdateReq) Reset() {
	*x = DeptUpdateReq{}
	mi := &file_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptUpdateReq) ProtoMessage() {}

func (x *DeptUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptUpdateReq.ProtoReflect.Descriptor instead.
func (*DeptUpdateReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{10}
}

func (x *DeptUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeptUpdateReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeptUpdateReq) GetParentCode() string {
	if x != nil {
		return x.ParentCode
	}
	return ""
}

func (x *DeptUpdateReq) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *DeptUpdateReq) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *DeptUpdateReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeptRemoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptRemoveReq) Reset() {
	*x = DeptRemoveReq{}
	mi := &file_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptRemoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptRemoveReq) ProtoMessage() {}

func (x *DeptRemoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptRemoveReq.ProtoReflect.Descriptor instead.
func (*DeptRemoveReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{11}
}

func (x *DeptRemoveReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// --- Post ---
type PostPageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       int32                  `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	PostName      string                 `protobuf:"bytes,3,opt,name=post_name,json=postName,proto3" json:"post_name,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostPageReq) Reset() {
	*x = PostPageReq{}
	mi := &file_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostPageReq) ProtoMessage() {}

func (x *PostPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostPageReq.ProtoReflect.Descriptor instead.
func (*PostPageReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{12}
}

func (x *PostPageReq) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *PostPageReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PostPageReq) GetPostName() string {
	if x != nil {
		return x.PostName
	}
	return ""
}

func (x *PostPageReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type PostDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	PostName      string                 `protobuf:"bytes,3,opt,name=post_name,json=postName,proto3" json:"post_name,omitempty"`
	OrderNum      int32                  `protobuf:"varint,4,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    string                 `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDetail) Reset() {
	*x = PostDetail{}
	mi := &file_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDetail) ProtoMessage() {}

func (x *PostDetail) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDetail.ProtoReflect.Descriptor instead.
func (*PostDetail) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{13}
}

func (x *PostDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PostDetail) GetPostName() string {
	if x != nil {
		return x.PostName
	}
	return ""
}

func (x *PostDetail) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *PostDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PostDetail) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type PostPageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Records       []*PostDetail          `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Current       int32                  `protobuf:"varint,4,opt,name=current,proto3" json:"current,omitempty"`
	Pages         int32                  `protobuf:"varint,5,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostPageResp) Reset() {
	*x = PostPageResp{}
	mi := &file_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostPageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostPageResp) ProtoMessage() {}

func (x *PostPageResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostPageResp.ProtoReflect.Descriptor instead.
func (*PostPageResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{14}
}

func (x *PostPageResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PostPageResp) GetRecords() []*PostDetail {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *PostPageResp) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PostPageResp) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *PostPageResp) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

type PostSaveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	PostName      string                 `protobuf:"bytes,2,opt,name=post_name,json=postName,proto3" json:"post_name,omitempty"`
	OrderNum      int32                  `protobuf:"varint,3,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostSaveReq) Reset() {
	*x = PostSaveReq{}
	mi := &file_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostSaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostSaveReq) ProtoMessage() {}

func (x *PostSaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostSaveReq.ProtoReflect.Descriptor instead.
func (*PostSaveReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{15}
}

func (x *PostSaveReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PostSaveReq) GetPostName() string {
	if x != nil {
		return x.PostName
	}
	return ""
}

func (x *PostSaveReq) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *PostSaveReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type PostUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	PostName      string                 `protobuf:"bytes,3,opt,name=post_name,json=postName,proto3" json:"post_name,omitempty"`
	OrderNum      int32                  `protobuf:"varint,4,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUpdateReq) Reset() {
	*x = PostUpdateReq{}
	mi := &file_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUpdateReq) ProtoMessage() {}

func (x *PostUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUpdateReq.ProtoReflect.Descriptor instead.
func (*PostUpdateReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{16}
}

func (x *PostUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostUpdateReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PostUpdateReq) GetPostName() string {
	if x != nil {
		return x.PostName
	}
	return ""
}

func (x *PostUpdateReq) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *PostUpdateReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type PostStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostStatusReq) Reset() {
	*x = PostStatusReq{}
	mi := &file_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStatusReq) ProtoMessage() {}

func (x *PostStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStatusReq.ProtoReflect.Descriptor instead.
func (*PostStatusReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{17}
}

func (x *PostStatusReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PostStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type PostRemoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRemoveReq) Reset() {
	*x = PostRemoveReq{}
	mi := &file_identity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRemoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRemoveReq) ProtoMessage() {}

func (x *PostRemoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRemoveReq.ProtoReflect.Descriptor instead.
func (*PostRemoveReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{18}
}

func (x *PostRemoveReq) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

// --- Menu ---
type MenuDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuCode      string                 `protobuf:"bytes,1,opt,name=menu_code,json=menuCode,proto3" json:"menu_code,omitempty"`
	ParentCode    string                 `protobuf:"bytes,2,opt,name=parent_code,json=parentCode,proto3" json:"parent_code,omitempty"`
	MenuName      string                 `protobuf:"bytes,3,opt,name=menu_name,json=menuName,proto3" json:"menu_name,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	MenuType      string                 `protobuf:"bytes,5,opt,name=menu_type,json=menuType,proto3" json:"menu_type,omitempty"`
	Perms         string                 `protobuf:"bytes,6,opt,name=perms,proto3" json:"perms,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	Component     string                 `protobuf:"bytes,8,opt,name=component,proto3" json:"component,omitempty"`
	OrderNum      int32                  `protobuf:"varint,9,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	Children      []*MenuDetail          `protobuf:"bytes,10,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuDetail) Reset() {
	*x = MenuDetail{}
	mi := &file_identity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuDetail) ProtoMessage() {}

func (x *MenuDetail) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuDetail.ProtoReflect.Descriptor instead.
func (*MenuDetail) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{19}
}

func (x *MenuDetail) GetMenuCode() string {
	if x != nil {
		return x.MenuCode
	}
	return ""
}

func (x *MenuDetail) GetParentCode() string {
	if x != nil {
		return x.ParentCode
	}
	return ""
}

func (x *MenuDetail) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *MenuDetail) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MenuDetail) GetMenuType() string {
	if x != nil {
		return x.MenuType
	}
	return ""
}

func (x *MenuDetail) GetPerms() string {
	if x != nil {
		return x.Perms
	}
	return ""
}

func (x *MenuDetail) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MenuDetail) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *MenuDetail) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *MenuDetail) GetChildren() []*MenuDetail {
	if x != nil {
		return x.Children
	}
	return nil
}

type MenuTreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MenuDetail          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuTreeResp) Reset() {
	*x = MenuTreeResp{}
	mi := &file_identity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuTreeResp) ProtoMessage() {}

func (x *MenuTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuTreeResp.ProtoReflect.Descriptor instead.
func (*MenuTreeResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{20}
}

func (x *MenuTreeResp) GetList() []*MenuDetail {
	if x != nil {
		return x.List
	}
	return nil
}

// --- Role ---
type RolePageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       int32                  `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePageReq) Reset() {
	*x = RolePageReq{}
	mi := &file_identity_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePageReq) ProtoMessage() {}

func (x *RolePageReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePageReq.ProtoReflect.Descriptor instead.
func (*RolePageReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{21}
}

func (x *RolePageReq) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *RolePageReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RolePageReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RolePageReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RoleDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleSort      int32                  `protobuf:"varint,4,opt,name=role_sort,json=roleSort,proto3" json:"role_sort,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    string                 `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Remark        string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleDetail) Reset() {
	*x = RoleDetail{}
	mi := &file_identity_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDetail) ProtoMessage() {}

func (x *RoleDetail) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDetail.ProtoReflect.Descriptor instead.
func (*RoleDetail) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{22}
}

func (x *RoleDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RoleDetail) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleDetail) GetRoleSort() int32 {
	if x != nil {
		return x.RoleSort
	}
	return 0
}

func (x *RoleDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleDetail) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *RoleDetail) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type RolePageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Records       []*RoleDetail          `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Current       int32                  `protobuf:"varint,4,opt,name=current,proto3" json:"current,omitempty"`
	Pages         int32                  `protobuf:"varint,5,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePageResp) Reset() {
	*x = RolePageResp{}
	mi := &file_identity_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePageResp) ProtoMessage() {}

func (x *RolePageResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePageResp.ProtoReflect.Descriptor instead.
func (*RolePageResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{23}
}

func (x *RolePageResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RolePageResp) GetRecords() []*RoleDetail {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *RolePageResp) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RolePageResp) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *RolePageResp) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

type RoleSubmitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	OrderNum      int32                  `protobuf:"varint,4,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleSubmitReq) Reset() {
	*x = RoleSubmitReq{}
	mi := &file_identity_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleSubmitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleSubmitReq) ProtoMessage() {}

func (x *RoleSubmitReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleSubmitReq.ProtoReflect.Descriptor instead.
func (*RoleSubmitReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{24}
}

func (x *RoleSubmitReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleSubmitReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RoleSubmitReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleSubmitReq) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *RoleSubmitReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleSubmitReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type RoleUpdateStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleUpdateStatusReq) Reset() {
	*x = RoleUpdateStatusReq{}
	mi := &file_identity_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleUpdateStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleUpdateStatusReq) ProtoMessage() {}

func (x *RoleUpdateStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleUpdateStatusReq.ProtoReflect.Descriptor instead.
func (*RoleUpdateStatusReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{25}
}

func (x *RoleUpdateStatusReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleUpdateStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RoleRemoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleRemoveReq) Reset() {
	*x = RoleRemoveReq{}
	mi := &file_identity_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleRemoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleRemoveReq) ProtoMessage() {}

func (x *RoleRemoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleRemoveReq.ProtoReflect.Descriptor instead.
func (*RoleRemoveReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{26}
}

func (x *RoleRemoveReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// --- User ---
type UserListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	RealName      string                 `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	DeptCode      string                 `protobuf:"bytes,5,opt,name=dept_code,json=deptCode,proto3" json:"dept_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListReq) Reset() {
	*x = UserListReq{}
	mi := &file_identity_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListReq) ProtoMessage() {}

func (x *UserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListReq.ProtoReflect.Descriptor instead.
func (*UserListReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{27}
}

func (x *UserListReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserListReq) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *UserListReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserListReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserListReq) GetDeptCode() string {
	if x != nil {
		return x.DeptCode
	}
	return ""
}

type UserDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	RealName      string                 `protobuf:"bytes,4,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Sex           int32                  `protobuf:"varint,7,opt,name=sex,proto3" json:"sex,omitempty"`
	DeptId        string                 `protobuf:"bytes,8,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	DeptName      string                 `protobuf:"bytes,9,opt,name=dept_name,json=deptName,proto3" json:"dept_name,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Avatar        string                 `protobuf:"bytes,11,opt,name=avatar,proto3" json:"avatar,omitempty"`
	RoleCodes     []string               `protobuf:"bytes,12,rep,name=role_codes,json=roleCodes,proto3" json:"role_codes,omitempty"`
	CreateTime    string                 `protobuf:"bytes,13,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetail) Reset() {
	*x = UserDetail{}
	mi := &file_identity_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetail) ProtoMessage() {}

func (x *UserDetail) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetail.ProtoReflect.Descriptor instead.
func (*UserDetail) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{28}
}

func (x *UserDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserDetail) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserDetail) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *UserDetail) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserDetail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDetail) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserDetail) GetDeptId() string {
	if x != nil {
		return x.DeptId
	}
	return ""
}

func (x *UserDetail) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *UserDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserDetail) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserDetail) GetRoleCodes() []string {
	if x != nil {
		return x.RoleCodes
	}
	return nil
}

func (x *UserDetail) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type UserListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserDetail          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResp) Reset() {
	*x = UserListResp{}
	mi := &file_identity_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResp) ProtoMessage() {}

func (x *UserListResp) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResp.ProtoReflect.Descriptor instead.
func (*UserListResp) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{29}
}

func (x *UserListResp) GetList() []*UserDetail {
	if x != nil {
		return x.List
	}
	return nil
}

type UserSubmitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	NickName      string                 `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	RealName      string                 `protobuf:"bytes,4,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	DeptCode      string                 `protobuf:"bytes,7,opt,name=dept_code,json=deptCode,proto3" json:"dept_code,omitempty"`
	Sex           int32                  `protobuf:"varint,8,opt,name=sex,proto3" json:"sex,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSubmitReq) Reset() {
	*x = UserSubmitReq{}
	mi := &file_identity_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSubmitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSubmitReq) ProtoMessage() {}

func (x *UserSubmitReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSubmitReq.ProtoReflect.Descriptor instead.
func (*UserSubmitReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{30}
}

func (x *UserSubmitReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserSubmitReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserSubmitReq) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserSubmitReq) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *UserSubmitReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserSubmitReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSubmitReq) GetDeptCode() string {
	if x != nil {
		return x.DeptCode
	}
	return ""
}

func (x *UserSubmitReq) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserSubmitReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UserUpdateStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateStatusReq) Reset() {
	*x = UserUpdateStatusReq{}
	mi := &file_identity_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateStatusReq) ProtoMessage() {}

func (x *UserUpdateStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateStatusReq.ProtoReflect.Descriptor instead.
func (*UserUpdateStatusReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{31}
}

func (x *UserUpdateStatusReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserUpdateStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UserResetPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResetPasswordReq) Reset() {
	*x = UserResetPasswordReq{}
	mi := &file_identity_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResetPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResetPasswordReq) ProtoMessage() {}

func (x *UserResetPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResetPasswordReq.ProtoReflect.Descriptor instead.
func (*UserResetPasswordReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{32}
}

func (x *UserResetPasswordReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserRemoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRemoveReq) Reset() {
	*x = UserRemoveReq{}
	mi := &file_identity_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRemoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRemoveReq) ProtoMessage() {}

func (x *UserRemoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRemoveReq.ProtoReflect.Descriptor instead.
func (*UserRemoveReq) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{33}
}

func (x *UserRemoveReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_identity_proto protoreflect.FileDescriptor

const file_identity_proto_rawDesc = "" +
	"\n" +
	"\x0eidentity.proto\x12\bidentity\"\n" +
	"\n" +
	"\bEmptyReq\"'\n" +
	"\vSuccessResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Q\n" +
	"\x12GetUserAuthInfoReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1f\n" +
	"\vtenant_code\x18\x02 \x01(\tR\n" +
	"tenantCode\"\x90\x01\n" +
	"\x13GetUserAuthInfoResp\x12\x1b\n" +
	"\tuser_code\x18\x01 \x01(\tR\buserCode\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12\x1f\n" +
	"\vtenant_code\x18\x03 \x01(\tR\n" +
	"tenantCode\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"N\n" +
	"\x0eGetUserInfoReq\x12\x1b\n" +
	"\tuser_code\x18\x01 \x01(\tR\buserCode\x12\x1f\n" +
	"\vtenant_code\x18\x02 \x01(\tR\n" +
	"tenantCode\"]\n" +
	"\n" +
	"UserEntity\x12\x1b\n" +
	"\tuser_code\x18\x01 \x01(\tR\buserCode\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"g\n" +
	"\x0fGetUserInfoResp\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.identity.UserEntityR\x04user\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12\x14\n" +
	"\x05perms\x18\x03 \x03(\tR\x05perms\"\x8a\x02\n" +
	"\n" +
	"DeptDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1f\n" +
	"\vparent_code\x18\x03 \x01(\tR\n" +
	"parentCode\x12\x12\n" +
	"\x04leaf\x18\x04 \x01(\x05R\x04leaf\x12\x1b\n" +
	"\tdept_name\x18\x05 \x01(\tR\bdeptName\x12\x1b\n" +
	"\torder_num\x18\x06 \x01(\x05R\borderNum\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\tR\n" +
	"createTime\x120\n" +
	"\bchildren\x18\t \x03(\v2\x14.identity.DeptDetailR\bchildren\"8\n" +
	"\fDeptTreeResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.identity.DeptDetailR\x04list\"\x94\x01\n" +
	"\vDeptSaveReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1f\n" +
	"\vparent_code\x18\x02 \x01(\tR\n" +
	"parentCode\x12\x1b\n" +
	"\tdept_name\x18\x03 \x01(\tR\bdeptName\x12\x1b\n" +
	"\torder_num\x18\x04 \x01(\x05R\borderNum\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"\xa6\x01\n" +
	"\rDeptUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1f\n" +
	"\vparent_code\x18\x03 \x01(\tR\n" +
	"parentCode\x12\x1b\n" +
	"\tdept_name\x18\x04 \x01(\tR\bdeptName\x12\x1b\n" +
	"\torder_num\x18\x05 \x01(\x05R\borderNum\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"!\n" +
	"\rDeptRemoveReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"p\n" +
	"\vPostPageReq\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\x05R\acurrent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x1b\n" +
	"\tpost_name\x18\x03 \x01(\tR\bpostName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\xa3\x01\n" +
	"\n" +
	"PostDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1b\n" +
	"\tpost_name\x18\x03 \x01(\tR\bpostName\x12\x1b\n" +
	"\torder_num\x18\x04 \x01(\x05R\borderNum\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\tR\n" +
	"createTime\"\x98\x01\n" +
	"\fPostPageResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12.\n" +
	"\arecords\x18\x02 \x03(\v2\x14.identity.PostDetailR\arecords\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x18\n" +
	"\acurrent\x18\x04 \x01(\x05R\acurrent\x12\x14\n" +
	"\x05pages\x18\x05 \x01(\x05R\x05pages\"s\n" +
	"\vPostSaveReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\tpost_name\x18\x02 \x01(\tR\bpostName\x12\x1b\n" +
	"\torder_num\x18\x03 \x01(\x05R\borderNum\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\x85\x01\n" +
	"\rPostUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1b\n" +
	"\tpost_name\x18\x03 \x01(\tR\bpostName\x12\x1b\n" +
	"\torder_num\x18\x04 \x01(\x05R\borderNum\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\";\n" +
	"\rPostStatusReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"%\n" +
	"\rPostRemoveReq\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\"\xaf\x02\n" +
	"\n" +
	"MenuDetail\x12\x1b\n" +
	"\tmenu_code\x18\x01 \x01(\tR\bmenuCode\x12\x1f\n" +
	"\vparent_code\x18\x02 \x01(\tR\n" +
	"parentCode\x12\x1b\n" +
	"\tmenu_name\x18\x03 \x01(\tR\bmenuName\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x1b\n" +
	"\tmenu_type\x18\x05 \x01(\tR\bmenuType\x12\x14\n" +
	"\x05perms\x18\x06 \x01(\tR\x05perms\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12\x1c\n" +
	"\tcomponent\x18\b \x01(\tR\tcomponent\x12\x1b\n" +
	"\torder_num\x18\t \x01(\x05R\borderNum\x120\n" +
	"\bchildren\x18\n" +
	" \x03(\v2\x14.identity.MenuDetailR\bchildren\"8\n" +
	"\fMenuTreeResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.identity.MenuDetailR\x04list\"p\n" +
	"\vRolePageReq\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\x05R\acurrent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x1b\n" +
	"\trole_name\x18\x03 \x01(\tR\broleName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\xbb\x01\n" +
	"\n" +
	"RoleDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1b\n" +
	"\trole_name\x18\x03 \x01(\tR\broleName\x12\x1b\n" +
	"\trole_sort\x18\x04 \x01(\x05R\broleSort\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\tR\n" +
	"createTime\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\"\x98\x01\n" +
	"\fRolePageResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12.\n" +
	"\arecords\x18\x02 \x03(\v2\x14.identity.RoleDetailR\arecords\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x18\n" +
	"\acurrent\x18\x04 \x01(\x05R\acurrent\x12\x14\n" +
	"\x05pages\x18\x05 \x01(\x05R\x05pages\"\x9d\x01\n" +
	"\rRoleSubmitReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1b\n" +
	"\trole_name\x18\x03 \x01(\tR\broleName\x12\x1b\n" +
	"\torder_num\x18\x04 \x01(\x05R\borderNum\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\"=\n" +
	"\x13RoleUpdateStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"!\n" +
	"\rRoleRemoveReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\x91\x01\n" +
	"\vUserListReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\treal_name\x18\x02 \x01(\tR\brealName\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1b\n" +
	"\tdept_code\x18\x05 \x01(\tR\bdeptCode\"\xcd\x02\n" +
	"\n" +
	"UserDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1b\n" +
	"\treal_name\x18\x04 \x01(\tR\brealName\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x10\n" +
	"\x03sex\x18\a \x01(\x05R\x03sex\x12\x17\n" +
	"\adept_id\x18\b \x01(\tR\x06deptId\x12\x1b\n" +
	"\tdept_name\x18\t \x01(\tR\bdeptName\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x16\n" +
	"\x06avatar\x18\v \x01(\tR\x06avatar\x12\x1d\n" +
	"\n" +
	"role_codes\x18\f \x03(\tR\troleCodes\x12\x1f\n" +
	"\vcreate_time\x18\r \x01(\tR\n" +
	"createTime\"8\n" +
	"\fUserListResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.identity.UserDetailR\x04list\"\xe0\x01\n" +
	"\rUserSubmitReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1b\n" +
	"\tnick_name\x18\x03 \x01(\tR\bnickName\x12\x1b\n" +
	"\treal_name\x18\x04 \x01(\tR\brealName\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x1b\n" +
	"\tdept_code\x18\a \x01(\tR\bdeptCode\x12\x10\n" +
	"\x03sex\x18\b \x01(\x05R\x03sex\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\"=\n" +
	"\x13UserUpdateStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"&\n" +
	"\x14UserResetPasswordReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\rUserRemoveReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids2\xc8\n" +
	"\n" +
	"\x0fIdentityService\x12N\n" +
	"\x0fGetUserAuthInfo\x12\x1c.identity.GetUserAuthInfoReq\x1a\x1d.identity.GetUserAuthInfoResp\x12B\n" +
	"\vGetUserInfo\x12\x18.identity.GetUserInfoReq\x1a\x19.identity.GetUserInfoResp\x126\n" +
	"\bDeptTree\x12\x12.identity.EmptyReq\x1a\x16.identity.DeptTreeResp\x128\n" +
	"\bDeptSave\x12\x15.identity.DeptSaveReq\x1a\x15.identity.SuccessResp\x12<\n" +
	"\n" +
	"DeptUpdate\x12\x17.identity.DeptUpdateReq\x1a\x15.identity.SuccessResp\x12<\n" +
	"\n" +
	"DeptRemove\x12\x17.identity.DeptRemoveReq\x1a\x15.identity.SuccessResp\x129\n" +
	"\bPostPage\x12\x15.identity.PostPageReq\x1a\x16.identity.PostPageResp\x128\n" +
	"\bPostSave\x12\x15.identity.PostSaveReq\x1a\x15.identity.SuccessResp\x12<\n" +
	"\n" +
	"PostUpdate\x12\x17.identity.PostUpdateReq\x1a\x15.identity.SuccessResp\x12<\n" +
	"\n" +
	"PostRemove\x12\x17.identity.PostRemoveReq\x1a\x15.identity.SuccessResp\x12<\n" +
	"\n" +
	"PostStatus\x12\x17.identity.PostStatusReq\x1a\x15.identity.SuccessResp\x126\n" +
	"\bMenuTree\x12\x12.identity.EmptyReq\x1a\x16.identity.MenuTreeResp\x129\n" +
	"\bRolePage\x12\x15.identity.RolePageReq\x1a\x16.identity.RolePageResp\x12<\n" +
	"\n" +
	"RoleSubmit\x12\x17.identity.RoleSubmitReq\x1a\x15.identity.SuccessResp\x12H\n" +
	"\x10RoleUpdateStatus\x12\x1d.identity.RoleUpdateStatusReq\x1a\x15.identity.SuccessResp\x12<\n" +
	"\n" +
	"RoleRemove\x12\x17.identity.RoleRemoveReq\x1a\x15.identity.SuccessResp\x129\n" +
	"\bUserList\x12\x15.identity.UserListReq\x1a\x16.identity.UserListResp\x12<\n" +
	"\n" +
	"UserSubmit\x12\x17.identity.UserSubmitReq\x1a\x15.identity.SuccessResp\x12H\n" +
	"\x10UserUpdateStatus\x12\x1d.identity.UserUpdateStatusReq\x1a\x15.identity.SuccessResp\x12J\n" +
	"\x11UserResetPassword\x12\x1e.identity.UserResetPasswordReq\x1a\x15.identity.SuccessResp\x12<\n" +
	"\n" +
	"UserRemove\x12\x17.identity.UserRemoveReq\x1a\x15.identity.SuccessRespB\x06Z\x04./pbb\x06proto3"

var (
	file_identity_proto_rawDescOnce sync.Once
	file_identity_proto_rawDescData []byte
)

func file_identity_proto_rawDescGZIP() []byte {
	file_identity_proto_rawDescOnce.Do(func() {
		file_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)))
	})
	return file_identity_proto_rawDescData
}

var file_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_identity_proto_goTypes = []any{
	(*EmptyReq)(nil),             // 0: identity.EmptyReq
	(*SuccessResp)(nil),          // 1: identity.SuccessResp
	(*GetUserAuthInfoReq)(nil),   // 2: identity.GetUserAuthInfoReq
	(*GetUserAuthInfoResp)(nil),  // 3: identity.GetUserAuthInfoResp
	(*GetUserInfoReq)(nil),       // 4: identity.GetUserInfoReq
	(*UserEntity)(nil),           // 5: identity.UserEntity
	(*GetUserInfoResp)(nil),      // 6: identity.GetUserInfoResp
	(*DeptDetail)(nil),           // 7: identity.DeptDetail
	(*DeptTreeResp)(nil),         // 8: identity.DeptTreeResp
	(*DeptSaveReq)(nil),          // 9: identity.DeptSaveReq
	(*DeptUpdateReq)(nil),        // 10: identity.DeptUpdateReq
	(*DeptRemoveReq)(nil),        // 11: identity.DeptRemoveReq
	(*PostPageReq)(nil),          // 12: identity.PostPageReq
	(*PostDetail)(nil),           // 13: identity.PostDetail
	(*PostPageResp)(nil),         // 14: identity.PostPageResp
	(*PostSaveReq)(nil),          // 15: identity.PostSaveReq
	(*PostUpdateReq)(nil),        // 16: identity.PostUpdateReq
	(*PostStatusReq)(nil),        // 17: identity.PostStatusReq
	(*PostRemoveReq)(nil),        // 18: identity.PostRemoveReq
	(*MenuDetail)(nil),           // 19: identity.MenuDetail
	(*MenuTreeResp)(nil),         // 20: identity.MenuTreeResp
	(*RolePageReq)(nil),          // 21: identity.RolePageReq
	(*RoleDetail)(nil),           // 22: identity.RoleDetail
	(*RolePageResp)(nil),         // 23: identity.RolePageResp
	(*RoleSubmitReq)(nil),        // 24: identity.RoleSubmitReq
	(*RoleUpdateStatusReq)(nil),  // 25: identity.RoleUpdateStatusReq
	(*RoleRemoveReq)(nil),        // 26: identity.RoleRemoveReq
	(*UserListReq)(nil),          // 27: identity.UserListReq
	(*UserDetail)(nil),           // 28: identity.UserDetail
	(*UserListResp)(nil),         // 29: identity.UserListResp
	(*UserSubmitReq)(nil),        // 30: identity.UserSubmitReq
	(*UserUpdateStatusReq)(nil),  // 31: identity.UserUpdateStatusReq
	(*UserResetPasswordReq)(nil), // 32: identity.UserResetPasswordReq
	(*UserRemoveReq)(nil),        // 33: identity.UserRemoveReq
}
var file_identity_proto_depIdxs = []int32{
	5,  // 0: identity.GetUserInfoResp.user:type_name -> identity.UserEntity
	7,  // 1: identity.DeptDetail.children:type_name -> identity.DeptDetail
	7,  // 2: identity.DeptTreeResp.list:type_name -> identity.DeptDetail
	13, // 3: identity.PostPageResp.records:type_name -> identity.PostDetail
	19, // 4: identity.MenuDetail.children:type_name -> identity.MenuDetail
	19, // 5: identity.MenuTreeResp.list:type_name -> identity.MenuDetail
	22, // 6: identity.RolePageResp.records:type_name -> identity.RoleDetail
	28, // 7: identity.UserListResp.list:type_name -> identity.UserDetail
	2,  // 8: identity.IdentityService.GetUserAuthInfo:input_type -> identity.GetUserAuthInfoReq
	4,  // 9: identity.IdentityService.GetUserInfo:input_type -> identity.GetUserInfoReq
	0,  // 10: identity.IdentityService.DeptTree:input_type -> identity.EmptyReq
	9,  // 11: identity.IdentityService.DeptSave:input_type -> identity.DeptSaveReq
	10, // 12: identity.IdentityService.DeptUpdate:input_type -> identity.DeptUpdateReq
	11, // 13: identity.IdentityService.DeptRemove:input_type -> identity.DeptRemoveReq
	12, // 14: identity.IdentityService.PostPage:input_type -> identity.PostPageReq
	15, // 15: identity.IdentityService.PostSave:input_type -> identity.PostSaveReq
	16, // 16: identity.IdentityService.PostUpdate:input_type -> identity.PostUpdateReq
	18, // 17: identity.IdentityService.PostRemove:input_type -> identity.PostRemoveReq
	17, // 18: identity.IdentityService.PostStatus:input_type -> identity.PostStatusReq
	0,  // 19: identity.IdentityService.MenuTree:input_type -> identity.EmptyReq
	21, // 20: identity.IdentityService.RolePage:input_type -> identity.RolePageReq
	24, // 21: identity.IdentityService.RoleSubmit:input_type -> identity.RoleSubmitReq
	25, // 22: identity.IdentityService.RoleUpdateStatus:input_type -> identity.RoleUpdateStatusReq
	26, // 23: identity.IdentityService.RoleRemove:input_type -> identity.RoleRemoveReq
	27, // 24: identity.IdentityService.UserList:input_type -> identity.UserListReq
	30, // 25: identity.IdentityService.UserSubmit:input_type -> identity.UserSubmitReq
	31, // 26: identity.IdentityService.UserUpdateStatus:input_type -> identity.UserUpdateStatusReq
	32, // 27: identity.IdentityService.UserResetPassword:input_type -> identity.UserResetPasswordReq
	33, // 28: identity.IdentityService.UserRemove:input_type -> identity.UserRemoveReq
	3,  // 29: identity.IdentityService.GetUserAuthInfo:output_type -> identity.GetUserAuthInfoResp
	6,  // 30: identity.IdentityService.GetUserInfo:output_type -> identity.GetUserInfoResp
	8,  // 31: identity.IdentityService.DeptTree:output_type -> identity.DeptTreeResp
	1,  // 32: identity.IdentityService.DeptSave:output_type -> identity.SuccessResp
	1,  // 33: identity.IdentityService.DeptUpdate:output_type -> identity.SuccessResp
	1,  // 34: identity.IdentityService.DeptRemove:output_type -> identity.SuccessResp
	14, // 35: identity.IdentityService.PostPage:output_type -> identity.PostPageResp
	1,  // 36: identity.IdentityService.PostSave:output_type -> identity.SuccessResp
	1,  // 37: identity.IdentityService.PostUpdate:output_type -> identity.SuccessResp
	1,  // 38: identity.IdentityService.PostRemove:output_type -> identity.SuccessResp
	1,  // 39: identity.IdentityService.PostStatus:output_type -> identity.SuccessResp
	20, // 40: identity.IdentityService.MenuTree:output_type -> identity.MenuTreeResp
	23, // 41: identity.IdentityService.RolePage:output_type -> identity.RolePageResp
	1,  // 42: identity.IdentityService.RoleSubmit:output_type -> identity.SuccessResp
	1,  // 43: identity.IdentityService.RoleUpdateStatus:output_type -> identity.SuccessResp
	1,  // 44: identity.IdentityService.RoleRemove:output_type -> identity.SuccessResp
	29, // 45: identity.IdentityService.UserList:output_type -> identity.UserListResp
	1,  // 46: identity.IdentityService.UserSubmit:output_type -> identity.SuccessResp
	1,  // 47: identity.IdentityService.UserUpdateStatus:output_type -> identity.SuccessResp
	1,  // 48: identity.IdentityService.UserResetPassword:output_type -> identity.SuccessResp
	1,  // 49: identity.IdentityService.UserRemove:output_type -> identity.SuccessResp
	29, // [29:50] is the sub-list for method output_type
	8,  // [8:29] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_identity_proto_init() }
func file_identity_proto_init() {
	if File_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_proto_goTypes,
		DependencyIndexes: file_identity_proto_depIdxs,
		MessageInfos:      file_identity_proto_msgTypes,
	}.Build()
	File_identity_proto = out.File
	file_identity_proto_goTypes = nil
	file_identity_proto_depIdxs = nil
}
