// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: app/identity/identity.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_GetUserAuthInfo_FullMethodName   = "/identity.IdentityService/GetUserAuthInfo"
	IdentityService_GetUserInfo_FullMethodName       = "/identity.IdentityService/GetUserInfo"
	IdentityService_DeptTree_FullMethodName          = "/identity.IdentityService/DeptTree"
	IdentityService_DeptSave_FullMethodName          = "/identity.IdentityService/DeptSave"
	IdentityService_DeptUpdate_FullMethodName        = "/identity.IdentityService/DeptUpdate"
	IdentityService_DeptRemove_FullMethodName        = "/identity.IdentityService/DeptRemove"
	IdentityService_PostPage_FullMethodName          = "/identity.IdentityService/PostPage"
	IdentityService_PostSave_FullMethodName          = "/identity.IdentityService/PostSave"
	IdentityService_PostUpdate_FullMethodName        = "/identity.IdentityService/PostUpdate"
	IdentityService_PostRemove_FullMethodName        = "/identity.IdentityService/PostRemove"
	IdentityService_PostStatus_FullMethodName        = "/identity.IdentityService/PostStatus"
	IdentityService_MenuTree_FullMethodName          = "/identity.IdentityService/MenuTree"
	IdentityService_MenuList_FullMethodName          = "/identity.IdentityService/MenuList"
	IdentityService_MenuDetail_FullMethodName        = "/identity.IdentityService/MenuDetail"
	IdentityService_MenuSave_FullMethodName          = "/identity.IdentityService/MenuSave"
	IdentityService_MenuUpdate_FullMethodName        = "/identity.IdentityService/MenuUpdate"
	IdentityService_MenuRemove_FullMethodName        = "/identity.IdentityService/MenuRemove"
	IdentityService_MenuStatus_FullMethodName        = "/identity.IdentityService/MenuStatus"
	IdentityService_RolePage_FullMethodName          = "/identity.IdentityService/RolePage"
	IdentityService_RoleSubmit_FullMethodName        = "/identity.IdentityService/RoleSubmit"
	IdentityService_RoleUpdateStatus_FullMethodName  = "/identity.IdentityService/RoleUpdateStatus"
	IdentityService_RoleRemove_FullMethodName        = "/identity.IdentityService/RoleRemove"
	IdentityService_RoleDetail_FullMethodName        = "/identity.IdentityService/RoleDetail"
	IdentityService_RoleMenuTree_FullMethodName      = "/identity.IdentityService/RoleMenuTree"
	IdentityService_RoleAssignMenus_FullMethodName   = "/identity.IdentityService/RoleAssignMenus"
	IdentityService_RoleDataScope_FullMethodName     = "/identity.IdentityService/RoleDataScope"
	IdentityService_UserList_FullMethodName          = "/identity.IdentityService/UserList"
	IdentityService_UserSubmit_FullMethodName        = "/identity.IdentityService/UserSubmit"
	IdentityService_UserUpdateStatus_FullMethodName  = "/identity.IdentityService/UserUpdateStatus"
	IdentityService_UserResetPassword_FullMethodName = "/identity.IdentityService/UserResetPassword"
	IdentityService_UserRemove_FullMethodName        = "/identity.IdentityService/UserRemove"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --- 服务定义 ---
type IdentityServiceClient interface {
	GetUserAuthInfo(ctx context.Context, in *GetUserAuthInfoReq, opts ...grpc.CallOption) (*GetUserAuthInfoResp, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
	// Dept
	DeptTree(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*DeptTreeResp, error)
	DeptSave(ctx context.Context, in *DeptSaveReq, opts ...grpc.CallOption) (*SuccessResp, error)
	DeptUpdate(ctx context.Context, in *DeptUpdateReq, opts ...grpc.CallOption) (*SuccessResp, error)
	DeptRemove(ctx context.Context, in *DeptRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error)
	// Post
	PostPage(ctx context.Context, in *PostPageReq, opts ...grpc.CallOption) (*PostPageResp, error)
	PostSave(ctx context.Context, in *PostSaveReq, opts ...grpc.CallOption) (*SuccessResp, error)
	PostUpdate(ctx context.Context, in *PostUpdateReq, opts ...grpc.CallOption) (*SuccessResp, error)
	PostRemove(ctx context.Context, in *PostRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error)
	PostStatus(ctx context.Context, in *PostStatusReq, opts ...grpc.CallOption) (*SuccessResp, error)
	// Menu
	MenuTree(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*MenuTreeResp, error)
	MenuList(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*MenuListResp, error)
	MenuDetail(ctx context.Context, in *MenuDetailReq, opts ...grpc.CallOption) (*MenuDetailResp, error)
	MenuSave(ctx context.Context, in *MenuSaveReq, opts ...grpc.CallOption) (*SuccessResp, error)
	MenuUpdate(ctx context.Context, in *MenuUpdateReq, opts ...grpc.CallOption) (*SuccessResp, error)
	MenuRemove(ctx context.Context, in *MenuRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error)
	MenuStatus(ctx context.Context, in *MenuStatusReq, opts ...grpc.CallOption) (*SuccessResp, error)
	// Role
	RolePage(ctx context.Context, in *RolePageReq, opts ...grpc.CallOption) (*RolePageResp, error)
	RoleSubmit(ctx context.Context, in *RoleSubmitReq, opts ...grpc.CallOption) (*SuccessResp, error)
	RoleUpdateStatus(ctx context.Context, in *RoleUpdateStatusReq, opts ...grpc.CallOption) (*SuccessResp, error)
	RoleRemove(ctx context.Context, in *RoleRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error)
	RoleDetail(ctx context.Context, in *RoleDetailReq, opts ...grpc.CallOption) (*RoleDetailResp, error)
	RoleMenuTree(ctx context.Context, in *RoleMenuTreeReq, opts ...grpc.CallOption) (*RoleMenuTreeResp, error)
	RoleAssignMenus(ctx context.Context, in *RoleAssignMenusReq, opts ...grpc.CallOption) (*SuccessResp, error)
	RoleDataScope(ctx context.Context, in *RoleDataScopeReq, opts ...grpc.CallOption) (*SuccessResp, error)
	// User
	UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error)
	UserSubmit(ctx context.Context, in *UserSubmitReq, opts ...grpc.CallOption) (*SuccessResp, error)
	UserUpdateStatus(ctx context.Context, in *UserUpdateStatusReq, opts ...grpc.CallOption) (*SuccessResp, error)
	UserResetPassword(ctx context.Context, in *UserResetPasswordReq, opts ...grpc.CallOption) (*SuccessResp, error)
	UserRemove(ctx context.Context, in *UserRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) GetUserAuthInfo(ctx context.Context, in *GetUserAuthInfoReq, opts ...grpc.CallOption) (*GetUserAuthInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAuthInfoResp)
	err := c.cc.Invoke(ctx, IdentityService_GetUserAuthInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResp)
	err := c.cc.Invoke(ctx, IdentityService_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) DeptTree(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*DeptTreeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeptTreeResp)
	err := c.cc.Invoke(ctx, IdentityService_DeptTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) DeptSave(ctx context.Context, in *DeptSaveReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_DeptSave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) DeptUpdate(ctx context.Context, in *DeptUpdateReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_DeptUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) DeptRemove(ctx context.Context, in *DeptRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_DeptRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) PostPage(ctx context.Context, in *PostPageReq, opts ...grpc.CallOption) (*PostPageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostPageResp)
	err := c.cc.Invoke(ctx, IdentityService_PostPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) PostSave(ctx context.Context, in *PostSaveReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_PostSave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) PostUpdate(ctx context.Context, in *PostUpdateReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_PostUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) PostRemove(ctx context.Context, in *PostRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_PostRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) PostStatus(ctx context.Context, in *PostStatusReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_PostStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) MenuTree(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*MenuTreeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuTreeResp)
	err := c.cc.Invoke(ctx, IdentityService_MenuTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) MenuList(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*MenuListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuListResp)
	err := c.cc.Invoke(ctx, IdentityService_MenuList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) MenuDetail(ctx context.Context, in *MenuDetailReq, opts ...grpc.CallOption) (*MenuDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuDetailResp)
	err := c.cc.Invoke(ctx, IdentityService_MenuDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) MenuSave(ctx context.Context, in *MenuSaveReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_MenuSave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) MenuUpdate(ctx context.Context, in *MenuUpdateReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_MenuUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) MenuRemove(ctx context.Context, in *MenuRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_MenuRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) MenuStatus(ctx context.Context, in *MenuStatusReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_MenuStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RolePage(ctx context.Context, in *RolePageReq, opts ...grpc.CallOption) (*RolePageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RolePageResp)
	err := c.cc.Invoke(ctx, IdentityService_RolePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RoleSubmit(ctx context.Context, in *RoleSubmitReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_RoleSubmit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RoleUpdateStatus(ctx context.Context, in *RoleUpdateStatusReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_RoleUpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RoleRemove(ctx context.Context, in *RoleRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_RoleRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RoleDetail(ctx context.Context, in *RoleDetailReq, opts ...grpc.CallOption) (*RoleDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleDetailResp)
	err := c.cc.Invoke(ctx, IdentityService_RoleDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RoleMenuTree(ctx context.Context, in *RoleMenuTreeReq, opts ...grpc.CallOption) (*RoleMenuTreeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleMenuTreeResp)
	err := c.cc.Invoke(ctx, IdentityService_RoleMenuTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RoleAssignMenus(ctx context.Context, in *RoleAssignMenusReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_RoleAssignMenus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RoleDataScope(ctx context.Context, in *RoleDataScopeReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_RoleDataScope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListResp)
	err := c.cc.Invoke(ctx, IdentityService_UserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) UserSubmit(ctx context.Context, in *UserSubmitReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_UserSubmit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) UserUpdateStatus(ctx context.Context, in *UserUpdateStatusReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_UserUpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) UserResetPassword(ctx context.Context, in *UserResetPasswordReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_UserResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) UserRemove(ctx context.Context, in *UserRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, IdentityService_UserRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
//
// --- 服务定义 ---
type IdentityServiceServer interface {
	GetUserAuthInfo(context.Context, *GetUserAuthInfoReq) (*GetUserAuthInfoResp, error)
	GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error)
	// Dept
	DeptTree(context.Context, *EmptyReq) (*DeptTreeResp, error)
	DeptSave(context.Context, *DeptSaveReq) (*SuccessResp, error)
	DeptUpdate(context.Context, *DeptUpdateReq) (*SuccessResp, error)
	DeptRemove(context.Context, *DeptRemoveReq) (*SuccessResp, error)
	// Post
	PostPage(context.Context, *PostPageReq) (*PostPageResp, error)
	PostSave(context.Context, *PostSaveReq) (*SuccessResp, error)
	PostUpdate(context.Context, *PostUpdateReq) (*SuccessResp, error)
	PostRemove(context.Context, *PostRemoveReq) (*SuccessResp, error)
	PostStatus(context.Context, *PostStatusReq) (*SuccessResp, error)
	// Menu
	MenuTree(context.Context, *EmptyReq) (*MenuTreeResp, error)
	MenuList(context.Context, *EmptyReq) (*MenuListResp, error)
	MenuDetail(context.Context, *MenuDetailReq) (*MenuDetailResp, error)
	MenuSave(context.Context, *MenuSaveReq) (*SuccessResp, error)
	MenuUpdate(context.Context, *MenuUpdateReq) (*SuccessResp, error)
	MenuRemove(context.Context, *MenuRemoveReq) (*SuccessResp, error)
	MenuStatus(context.Context, *MenuStatusReq) (*SuccessResp, error)
	// Role
	RolePage(context.Context, *RolePageReq) (*RolePageResp, error)
	RoleSubmit(context.Context, *RoleSubmitReq) (*SuccessResp, error)
	RoleUpdateStatus(context.Context, *RoleUpdateStatusReq) (*SuccessResp, error)
	RoleRemove(context.Context, *RoleRemoveReq) (*SuccessResp, error)
	RoleDetail(context.Context, *RoleDetailReq) (*RoleDetailResp, error)
	RoleMenuTree(context.Context, *RoleMenuTreeReq) (*RoleMenuTreeResp, error)
	RoleAssignMenus(context.Context, *RoleAssignMenusReq) (*SuccessResp, error)
	RoleDataScope(context.Context, *RoleDataScopeReq) (*SuccessResp, error)
	// User
	UserList(context.Context, *UserListReq) (*UserListResp, error)
	UserSubmit(context.Context, *UserSubmitReq) (*SuccessResp, error)
	UserUpdateStatus(context.Context, *UserUpdateStatusReq) (*SuccessResp, error)
	UserResetPassword(context.Context, *UserResetPasswordReq) (*SuccessResp, error)
	UserRemove(context.Context, *UserRemoveReq) (*SuccessResp, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) GetUserAuthInfo(context.Context, *GetUserAuthInfoReq) (*GetUserAuthInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserAuthInfo not implemented")
}
func (UnimplementedIdentityServiceServer) GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedIdentityServiceServer) DeptTree(context.Context, *EmptyReq) (*DeptTreeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeptTree not implemented")
}
func (UnimplementedIdentityServiceServer) DeptSave(context.Context, *DeptSaveReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeptSave not implemented")
}
func (UnimplementedIdentityServiceServer) DeptUpdate(context.Context, *DeptUpdateReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeptUpdate not implemented")
}
func (UnimplementedIdentityServiceServer) DeptRemove(context.Context, *DeptRemoveReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeptRemove not implemented")
}
func (UnimplementedIdentityServiceServer) PostPage(context.Context, *PostPageReq) (*PostPageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PostPage not implemented")
}
func (UnimplementedIdentityServiceServer) PostSave(context.Context, *PostSaveReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PostSave not implemented")
}
func (UnimplementedIdentityServiceServer) PostUpdate(context.Context, *PostUpdateReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PostUpdate not implemented")
}
func (UnimplementedIdentityServiceServer) PostRemove(context.Context, *PostRemoveReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PostRemove not implemented")
}
func (UnimplementedIdentityServiceServer) PostStatus(context.Context, *PostStatusReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PostStatus not implemented")
}
func (UnimplementedIdentityServiceServer) MenuTree(context.Context, *EmptyReq) (*MenuTreeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuTree not implemented")
}
func (UnimplementedIdentityServiceServer) MenuList(context.Context, *EmptyReq) (*MenuListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuList not implemented")
}
func (UnimplementedIdentityServiceServer) MenuDetail(context.Context, *MenuDetailReq) (*MenuDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuDetail not implemented")
}
func (UnimplementedIdentityServiceServer) MenuSave(context.Context, *MenuSaveReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuSave not implemented")
}
func (UnimplementedIdentityServiceServer) MenuUpdate(context.Context, *MenuUpdateReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuUpdate not implemented")
}
func (UnimplementedIdentityServiceServer) MenuRemove(context.Context, *MenuRemoveReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuRemove not implemented")
}
func (UnimplementedIdentityServiceServer) MenuStatus(context.Context, *MenuStatusReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MenuStatus not implemented")
}
func (UnimplementedIdentityServiceServer) RolePage(context.Context, *RolePageReq) (*RolePageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RolePage not implemented")
}
func (UnimplementedIdentityServiceServer) RoleSubmit(context.Context, *RoleSubmitReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleSubmit not implemented")
}
func (UnimplementedIdentityServiceServer) RoleUpdateStatus(context.Context, *RoleUpdateStatusReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleUpdateStatus not implemented")
}
func (UnimplementedIdentityServiceServer) RoleRemove(context.Context, *RoleRemoveReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleRemove not implemented")
}
func (UnimplementedIdentityServiceServer) RoleDetail(context.Context, *RoleDetailReq) (*RoleDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleDetail not implemented")
}
func (UnimplementedIdentityServiceServer) RoleMenuTree(context.Context, *RoleMenuTreeReq) (*RoleMenuTreeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleMenuTree not implemented")
}
func (UnimplementedIdentityServiceServer) RoleAssignMenus(context.Context, *RoleAssignMenusReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleAssignMenus not implemented")
}
func (UnimplementedIdentityServiceServer) RoleDataScope(context.Context, *RoleDataScopeReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RoleDataScope not implemented")
}
func (UnimplementedIdentityServiceServer) UserList(context.Context, *UserListReq) (*UserListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserList not implemented")
}
func (UnimplementedIdentityServiceServer) UserSubmit(context.Context, *UserSubmitReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserSubmit not implemented")
}
func (UnimplementedIdentityServiceServer) UserUpdateStatus(context.Context, *UserUpdateStatusReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserUpdateStatus not implemented")
}
func (UnimplementedIdentityServiceServer) UserResetPassword(context.Context, *UserResetPasswordReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserResetPassword not implemented")
}
func (UnimplementedIdentityServiceServer) UserRemove(context.Context, *UserRemoveReq) (*SuccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserRemove not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_GetUserAuthInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAuthInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUserAuthInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUserAuthInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUserAuthInfo(ctx, req.(*GetUserAuthInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_DeptTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).DeptTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_DeptTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).DeptTree(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_DeptSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeptSaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).DeptSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_DeptSave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).DeptSave(ctx, req.(*DeptSaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_DeptUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeptUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).DeptUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_DeptUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).DeptUpdate(ctx, req.(*DeptUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_DeptRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeptRemoveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).DeptRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_DeptRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).DeptRemove(ctx, req.(*DeptRemoveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_PostPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).PostPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_PostPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).PostPage(ctx, req.(*PostPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_PostSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostSaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).PostSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_PostSave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).PostSave(ctx, req.(*PostSaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_PostUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).PostUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_PostUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).PostUpdate(ctx, req.(*PostUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_PostRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRemoveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).PostRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_PostRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).PostRemove(ctx, req.(*PostRemoveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_PostStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).PostStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_PostStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).PostStatus(ctx, req.(*PostStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_MenuTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).MenuTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_MenuTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).MenuTree(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_MenuList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).MenuList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_MenuList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).MenuList(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_MenuDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).MenuDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_MenuDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).MenuDetail(ctx, req.(*MenuDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_MenuSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuSaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).MenuSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_MenuSave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).MenuSave(ctx, req.(*MenuSaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_MenuUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).MenuUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_MenuUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).MenuUpdate(ctx, req.(*MenuUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_MenuRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuRemoveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).MenuRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_MenuRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).MenuRemove(ctx, req.(*MenuRemoveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_MenuStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).MenuStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_MenuStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).MenuStatus(ctx, req.(*MenuStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RolePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolePageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RolePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RolePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RolePage(ctx, req.(*RolePageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RoleSubmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleSubmitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RoleSubmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RoleSubmit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RoleSubmit(ctx, req.(*RoleSubmitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RoleUpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleUpdateStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RoleUpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RoleUpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RoleUpdateStatus(ctx, req.(*RoleUpdateStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RoleRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleRemoveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RoleRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RoleRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RoleRemove(ctx, req.(*RoleRemoveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RoleDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RoleDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RoleDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RoleDetail(ctx, req.(*RoleDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RoleMenuTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleMenuTreeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RoleMenuTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RoleMenuTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RoleMenuTree(ctx, req.(*RoleMenuTreeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RoleAssignMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleAssignMenusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RoleAssignMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RoleAssignMenus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RoleAssignMenus(ctx, req.(*RoleAssignMenusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RoleDataScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleDataScopeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RoleDataScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RoleDataScope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RoleDataScope(ctx, req.(*RoleDataScopeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_UserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).UserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_UserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).UserList(ctx, req.(*UserListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_UserSubmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSubmitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).UserSubmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_UserSubmit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).UserSubmit(ctx, req.(*UserSubmitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_UserUpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).UserUpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_UserUpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).UserUpdateStatus(ctx, req.(*UserUpdateStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_UserResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserResetPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).UserResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_UserResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).UserResetPassword(ctx, req.(*UserResetPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_UserRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRemoveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).UserRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_UserRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).UserRemove(ctx, req.(*UserRemoveReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserAuthInfo",
			Handler:    _IdentityService_GetUserAuthInfo_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _IdentityService_GetUserInfo_Handler,
		},
		{
			MethodName: "DeptTree",
			Handler:    _IdentityService_DeptTree_Handler,
		},
		{
			MethodName: "DeptSave",
			Handler:    _IdentityService_DeptSave_Handler,
		},
		{
			MethodName: "DeptUpdate",
			Handler:    _IdentityService_DeptUpdate_Handler,
		},
		{
			MethodName: "DeptRemove",
			Handler:    _IdentityService_DeptRemove_Handler,
		},
		{
			MethodName: "PostPage",
			Handler:    _IdentityService_PostPage_Handler,
		},
		{
			MethodName: "PostSave",
			Handler:    _IdentityService_PostSave_Handler,
		},
		{
			MethodName: "PostUpdate",
			Handler:    _IdentityService_PostUpdate_Handler,
		},
		{
			MethodName: "PostRemove",
			Handler:    _IdentityService_PostRemove_Handler,
		},
		{
			MethodName: "PostStatus",
			Handler:    _IdentityService_PostStatus_Handler,
		},
		{
			MethodName: "MenuTree",
			Handler:    _IdentityService_MenuTree_Handler,
		},
		{
			MethodName: "MenuList",
			Handler:    _IdentityService_MenuList_Handler,
		},
		{
			MethodName: "MenuDetail",
			Handler:    _IdentityService_MenuDetail_Handler,
		},
		{
			MethodName: "MenuSave",
			Handler:    _IdentityService_MenuSave_Handler,
		},
		{
			MethodName: "MenuUpdate",
			Handler:    _IdentityService_MenuUpdate_Handler,
		},
		{
			MethodName: "MenuRemove",
			Handler:    _IdentityService_MenuRemove_Handler,
		},
		{
			MethodName: "MenuStatus",
			Handler:    _IdentityService_MenuStatus_Handler,
		},
		{
			MethodName: "RolePage",
			Handler:    _IdentityService_RolePage_Handler,
		},
		{
			MethodName: "RoleSubmit",
			Handler:    _IdentityService_RoleSubmit_Handler,
		},
		{
			MethodName: "RoleUpdateStatus",
			Handler:    _IdentityService_RoleUpdateStatus_Handler,
		},
		{
			MethodName: "RoleRemove",
			Handler:    _IdentityService_RoleRemove_Handler,
		},
		{
			MethodName: "RoleDetail",
			Handler:    _IdentityService_RoleDetail_Handler,
		},
		{
			MethodName: "RoleMenuTree",
			Handler:    _IdentityService_RoleMenuTree_Handler,
		},
		{
			MethodName: "RoleAssignMenus",
			Handler:    _IdentityService_RoleAssignMenus_Handler,
		},
		{
			MethodName: "RoleDataScope",
			Handler:    _IdentityService_RoleDataScope_Handler,
		},
		{
			MethodName: "UserList",
			Handler:    _IdentityService_UserList_Handler,
		},
		{
			MethodName: "UserSubmit",
			Handler:    _IdentityService_UserSubmit_Handler,
		},
		{
			MethodName: "UserUpdateStatus",
			Handler:    _IdentityService_UserUpdateStatus_Handler,
		},
		{
			MethodName: "UserResetPassword",
			Handler:    _IdentityService_UserResetPassword_Handler,
		},
		{
			MethodName: "UserRemove",
			Handler:    _IdentityService_UserRemove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/identity/identity.proto",
}
