// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: identity.proto

package server

import (
	"context"

	"zephyr-go/app/identity/internal/logic"
	"zephyr-go/app/identity/internal/svc"
	"zephyr-go/app/identity/pb"
)

type IdentityServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedIdentityServiceServer
}

func NewIdentityServiceServer(svcCtx *svc.ServiceContext) *IdentityServiceServer {
	return &IdentityServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *IdentityServiceServer) GetUserAuthInfo(ctx context.Context, in *pb.GetUserAuthInfoReq) (*pb.GetUserAuthInfoResp, error) {
	l := logic.NewGetUserAuthInfoLogic(ctx, s.svcCtx)
	return l.GetUserAuthInfo(in)
}

func (s *IdentityServiceServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

// Dept
func (s *IdentityServiceServer) DeptTree(ctx context.Context, in *pb.EmptyReq) (*pb.DeptTreeResp, error) {
	l := logic.NewDeptTreeLogic(ctx, s.svcCtx)
	return l.DeptTree(in)
}

func (s *IdentityServiceServer) DeptSave(ctx context.Context, in *pb.DeptSaveReq) (*pb.SuccessResp, error) {
	l := logic.NewDeptSaveLogic(ctx, s.svcCtx)
	return l.DeptSave(in)
}

func (s *IdentityServiceServer) DeptUpdate(ctx context.Context, in *pb.DeptUpdateReq) (*pb.SuccessResp, error) {
	l := logic.NewDeptUpdateLogic(ctx, s.svcCtx)
	return l.DeptUpdate(in)
}

func (s *IdentityServiceServer) DeptRemove(ctx context.Context, in *pb.DeptRemoveReq) (*pb.SuccessResp, error) {
	l := logic.NewDeptRemoveLogic(ctx, s.svcCtx)
	return l.DeptRemove(in)
}

// Post
func (s *IdentityServiceServer) PostPage(ctx context.Context, in *pb.PostPageReq) (*pb.PostPageResp, error) {
	l := logic.NewPostPageLogic(ctx, s.svcCtx)
	return l.PostPage(in)
}

func (s *IdentityServiceServer) PostSave(ctx context.Context, in *pb.PostSaveReq) (*pb.SuccessResp, error) {
	l := logic.NewPostSaveLogic(ctx, s.svcCtx)
	return l.PostSave(in)
}

func (s *IdentityServiceServer) PostUpdate(ctx context.Context, in *pb.PostUpdateReq) (*pb.SuccessResp, error) {
	l := logic.NewPostUpdateLogic(ctx, s.svcCtx)
	return l.PostUpdate(in)
}

func (s *IdentityServiceServer) PostRemove(ctx context.Context, in *pb.PostRemoveReq) (*pb.SuccessResp, error) {
	l := logic.NewPostRemoveLogic(ctx, s.svcCtx)
	return l.PostRemove(in)
}

func (s *IdentityServiceServer) PostStatus(ctx context.Context, in *pb.PostStatusReq) (*pb.SuccessResp, error) {
	l := logic.NewPostStatusLogic(ctx, s.svcCtx)
	return l.PostStatus(in)
}

// Menu
func (s *IdentityServiceServer) MenuTree(ctx context.Context, in *pb.EmptyReq) (*pb.MenuTreeResp, error) {
	l := logic.NewMenuTreeLogic(ctx, s.svcCtx)
	return l.MenuTree(in)
}

// Role
func (s *IdentityServiceServer) RolePage(ctx context.Context, in *pb.RolePageReq) (*pb.RolePageResp, error) {
	l := logic.NewRolePageLogic(ctx, s.svcCtx)
	return l.RolePage(in)
}

func (s *IdentityServiceServer) RoleSubmit(ctx context.Context, in *pb.RoleSubmitReq) (*pb.SuccessResp, error) {
	l := logic.NewRoleSubmitLogic(ctx, s.svcCtx)
	return l.RoleSubmit(in)
}

func (s *IdentityServiceServer) RoleUpdateStatus(ctx context.Context, in *pb.RoleUpdateStatusReq) (*pb.SuccessResp, error) {
	l := logic.NewRoleUpdateStatusLogic(ctx, s.svcCtx)
	return l.RoleUpdateStatus(in)
}

func (s *IdentityServiceServer) RoleRemove(ctx context.Context, in *pb.RoleRemoveReq) (*pb.SuccessResp, error) {
	l := logic.NewRoleRemoveLogic(ctx, s.svcCtx)
	return l.RoleRemove(in)
}

// User
func (s *IdentityServiceServer) UserList(ctx context.Context, in *pb.UserListReq) (*pb.UserListResp, error) {
	l := logic.NewUserListLogic(ctx, s.svcCtx)
	return l.UserList(in)
}

func (s *IdentityServiceServer) UserSubmit(ctx context.Context, in *pb.UserSubmitReq) (*pb.SuccessResp, error) {
	l := logic.NewUserSubmitLogic(ctx, s.svcCtx)
	return l.UserSubmit(in)
}

func (s *IdentityServiceServer) UserUpdateStatus(ctx context.Context, in *pb.UserUpdateStatusReq) (*pb.SuccessResp, error) {
	l := logic.NewUserUpdateStatusLogic(ctx, s.svcCtx)
	return l.UserUpdateStatus(in)
}

func (s *IdentityServiceServer) UserResetPassword(ctx context.Context, in *pb.UserResetPasswordReq) (*pb.SuccessResp, error) {
	l := logic.NewUserResetPasswordLogic(ctx, s.svcCtx)
	return l.UserResetPassword(in)
}

func (s *IdentityServiceServer) UserRemove(ctx context.Context, in *pb.UserRemoveReq) (*pb.SuccessResp, error) {
	l := logic.NewUserRemoveLogic(ctx, s.svcCtx)
	return l.UserRemove(in)
}
