// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "zephyr-go/app/gateway/internal/handler/auth"
	dept "zephyr-go/app/gateway/internal/handler/dept"
	identity "zephyr-go/app/gateway/internal/handler/identity"
	menu "zephyr-go/app/gateway/internal/handler/menu"
	post "zephyr-go/app/gateway/internal/handler/post"
	role "zephyr-go/app/gateway/internal/handler/role"
	user "zephyr-go/app/gateway/internal/handler/user"
	"zephyr-go/app/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// 退出登录
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
			{
				// 刷新Token
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: auth.RefreshHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/remove",
				Handler: dept.DeptRemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/save",
				Handler: dept.DeptSaveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tree",
				Handler: dept.DeptTreeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: dept.DeptUpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/system/dept"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取当前登录用户信息
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: identity.GetUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/tree",
				Handler: menu.MenuTreeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/system/menu"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: post.PostPageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/remove",
				Handler: post.PostRemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/save",
				Handler: post.PostSaveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/status",
				Handler: post.PostStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: post.PostUpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/system/post"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: role.RolePageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/remove",
				Handler: role.RoleRemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/submit",
				Handler: role.RoleSubmitHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateStatus",
				Handler: role.RoleUpdateStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/system/role"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: user.UserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/remove",
				Handler: user.UserRemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resetPassword",
				Handler: user.UserResetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/submit",
				Handler: user.UserSubmitHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateStatus",
				Handler: user.UserUpdateStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/system/user"),
	)
}
