// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: identity.proto

package identityservice

import (
	"context"

	"zephyr-go/app/identity/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeptDetail           = pb.DeptDetail
	DeptRemoveReq        = pb.DeptRemoveReq
	DeptSaveReq          = pb.DeptSaveReq
	DeptTreeResp         = pb.DeptTreeResp
	DeptUpdateReq        = pb.DeptUpdateReq
	EmptyReq             = pb.EmptyReq
	GetUserAuthInfoReq   = pb.GetUserAuthInfoReq
	GetUserAuthInfoResp  = pb.GetUserAuthInfoResp
	GetUserInfoReq       = pb.GetUserInfoReq
	GetUserInfoResp      = pb.GetUserInfoResp
	MenuDetail           = pb.MenuDetail
	MenuTreeResp         = pb.MenuTreeResp
	PostDetail           = pb.PostDetail
	PostPageReq          = pb.PostPageReq
	PostPageResp         = pb.PostPageResp
	PostRemoveReq        = pb.PostRemoveReq
	PostSaveReq          = pb.PostSaveReq
	PostStatusReq        = pb.PostStatusReq
	PostUpdateReq        = pb.PostUpdateReq
	RoleDetail           = pb.RoleDetail
	RolePageReq          = pb.RolePageReq
	RolePageResp         = pb.RolePageResp
	RoleRemoveReq        = pb.RoleRemoveReq
	RoleSubmitReq        = pb.RoleSubmitReq
	RoleUpdateStatusReq  = pb.RoleUpdateStatusReq
	SuccessResp          = pb.SuccessResp
	UserDetail           = pb.UserDetail
	UserEntity           = pb.UserEntity
	UserListReq          = pb.UserListReq
	UserListResp         = pb.UserListResp
	UserRemoveReq        = pb.UserRemoveReq
	UserResetPasswordReq = pb.UserResetPasswordReq
	UserSubmitReq        = pb.UserSubmitReq
	UserUpdateStatusReq  = pb.UserUpdateStatusReq

	IdentityService interface {
		GetUserAuthInfo(ctx context.Context, in *GetUserAuthInfoReq, opts ...grpc.CallOption) (*GetUserAuthInfoResp, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		// Dept
		DeptTree(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*DeptTreeResp, error)
		DeptSave(ctx context.Context, in *DeptSaveReq, opts ...grpc.CallOption) (*SuccessResp, error)
		DeptUpdate(ctx context.Context, in *DeptUpdateReq, opts ...grpc.CallOption) (*SuccessResp, error)
		DeptRemove(ctx context.Context, in *DeptRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error)
		// Post
		PostPage(ctx context.Context, in *PostPageReq, opts ...grpc.CallOption) (*PostPageResp, error)
		PostSave(ctx context.Context, in *PostSaveReq, opts ...grpc.CallOption) (*SuccessResp, error)
		PostUpdate(ctx context.Context, in *PostUpdateReq, opts ...grpc.CallOption) (*SuccessResp, error)
		PostRemove(ctx context.Context, in *PostRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error)
		PostStatus(ctx context.Context, in *PostStatusReq, opts ...grpc.CallOption) (*SuccessResp, error)
		// Menu
		MenuTree(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*MenuTreeResp, error)
		// Role
		RolePage(ctx context.Context, in *RolePageReq, opts ...grpc.CallOption) (*RolePageResp, error)
		RoleSubmit(ctx context.Context, in *RoleSubmitReq, opts ...grpc.CallOption) (*SuccessResp, error)
		RoleUpdateStatus(ctx context.Context, in *RoleUpdateStatusReq, opts ...grpc.CallOption) (*SuccessResp, error)
		RoleRemove(ctx context.Context, in *RoleRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error)
		// User
		UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error)
		UserSubmit(ctx context.Context, in *UserSubmitReq, opts ...grpc.CallOption) (*SuccessResp, error)
		UserUpdateStatus(ctx context.Context, in *UserUpdateStatusReq, opts ...grpc.CallOption) (*SuccessResp, error)
		UserResetPassword(ctx context.Context, in *UserResetPasswordReq, opts ...grpc.CallOption) (*SuccessResp, error)
		UserRemove(ctx context.Context, in *UserRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error)
	}

	defaultIdentityService struct {
		cli zrpc.Client
	}
)

func NewIdentityService(cli zrpc.Client) IdentityService {
	return &defaultIdentityService{
		cli: cli,
	}
}

func (m *defaultIdentityService) GetUserAuthInfo(ctx context.Context, in *GetUserAuthInfoReq, opts ...grpc.CallOption) (*GetUserAuthInfoResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.GetUserAuthInfo(ctx, in, opts...)
}

func (m *defaultIdentityService) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

// Dept
func (m *defaultIdentityService) DeptTree(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*DeptTreeResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.DeptTree(ctx, in, opts...)
}

func (m *defaultIdentityService) DeptSave(ctx context.Context, in *DeptSaveReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.DeptSave(ctx, in, opts...)
}

func (m *defaultIdentityService) DeptUpdate(ctx context.Context, in *DeptUpdateReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.DeptUpdate(ctx, in, opts...)
}

func (m *defaultIdentityService) DeptRemove(ctx context.Context, in *DeptRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.DeptRemove(ctx, in, opts...)
}

// Post
func (m *defaultIdentityService) PostPage(ctx context.Context, in *PostPageReq, opts ...grpc.CallOption) (*PostPageResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.PostPage(ctx, in, opts...)
}

func (m *defaultIdentityService) PostSave(ctx context.Context, in *PostSaveReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.PostSave(ctx, in, opts...)
}

func (m *defaultIdentityService) PostUpdate(ctx context.Context, in *PostUpdateReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.PostUpdate(ctx, in, opts...)
}

func (m *defaultIdentityService) PostRemove(ctx context.Context, in *PostRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.PostRemove(ctx, in, opts...)
}

func (m *defaultIdentityService) PostStatus(ctx context.Context, in *PostStatusReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.PostStatus(ctx, in, opts...)
}

// Menu
func (m *defaultIdentityService) MenuTree(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*MenuTreeResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.MenuTree(ctx, in, opts...)
}

// Role
func (m *defaultIdentityService) RolePage(ctx context.Context, in *RolePageReq, opts ...grpc.CallOption) (*RolePageResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.RolePage(ctx, in, opts...)
}

func (m *defaultIdentityService) RoleSubmit(ctx context.Context, in *RoleSubmitReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.RoleSubmit(ctx, in, opts...)
}

func (m *defaultIdentityService) RoleUpdateStatus(ctx context.Context, in *RoleUpdateStatusReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.RoleUpdateStatus(ctx, in, opts...)
}

func (m *defaultIdentityService) RoleRemove(ctx context.Context, in *RoleRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.RoleRemove(ctx, in, opts...)
}

// User
func (m *defaultIdentityService) UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.UserList(ctx, in, opts...)
}

func (m *defaultIdentityService) UserSubmit(ctx context.Context, in *UserSubmitReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.UserSubmit(ctx, in, opts...)
}

func (m *defaultIdentityService) UserUpdateStatus(ctx context.Context, in *UserUpdateStatusReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.UserUpdateStatus(ctx, in, opts...)
}

func (m *defaultIdentityService) UserResetPassword(ctx context.Context, in *UserResetPasswordReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.UserResetPassword(ctx, in, opts...)
}

func (m *defaultIdentityService) UserRemove(ctx context.Context, in *UserRemoveReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := pb.NewIdentityServiceClient(m.cli.Conn())
	return client.UserRemove(ctx, in, opts...)
}
