// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type DeptDetail struct {
	Id         string       `json:"id"`
	Code       string       `json:"code"`
	ParentCode string       `json:"parentCode,optional"`
	Leaf       int32        `json:"leaf"`
	DeptName   string       `json:"deptName"`
	OrderNum   int32        `json:"orderNum"`
	Status     int32        `json:"status"`
	CreateTime string       `json:"createTime"`
	Children   []DeptDetail `json:"children,optional"`
}

type DeptRemoveReq struct {
	Ids []string `json:"ids"`
}

type DeptSaveReq struct {
	Code       string `json:"code"`
	ParentCode string `json:"parentCode,optional"`
	DeptName   string `json:"deptName"`
	OrderNum   int32  `json:"orderNum"`
	Status     int32  `json:"status,optional"`
}

type DeptTreeResp struct {
	List []DeptDetail `json:"list"`
}

type DeptUpdateReq struct {
	Id         string `json:"id"`
	Code       string `json:"code"`
	ParentCode string `json:"parentCode,optional"`
	DeptName   string `json:"deptName"`
	OrderNum   int32  `json:"orderNum"`
	Status     int32  `json:"status,optional"`
}

type LoginReq struct {
	TenantCode string `json:"tenantCode,optional"`
	Username   string `json:"username"`
	Password   string `json:"password"`
}

type LoginResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"-"`
	AccessExpire int64  `json:"-"`
}

type MenuDetail struct {
	MenuCode   string       `json:"menuCode"`
	ParentCode string       `json:"parentCode"`
	MenuName   string       `json:"menuName"`
	Icon       string       `json:"icon"`
	MenuType   string       `json:"menuType"` // M/C/F
	Perms      string       `json:"perms"`
	Path       string       `json:"path"`
	Component  string       `json:"component"`
	OrderNum   int32        `json:"orderNum"`
	Children   []MenuDetail `json:"children,optional"`
}

type MenuTreeResp struct {
	List []MenuDetail `json:"list"`
}

type PostDetail struct {
	Id         int64  `json:"id"`
	Code       string `json:"code"`
	PostName   string `json:"postName"`
	OrderNum   int32  `json:"orderNum"`
	Status     int32  `json:"status"`
	CreateTime string `json:"createTime"`
}

type PostPageReq struct {
	Current  int    `form:"current,default=1"`
	Size     int    `form:"size,default=10"`
	PostName string `form:"postName,optional"`
	Status   int32  `form:"status,optional"`
}

type PostPageResp struct {
	Total   int64        `json:"total"`
	Records []PostDetail `json:"records"`
	Size    int          `json:"size"`
	Current int          `json:"current"`
	Pages   int          `json:"pages"`
}

type PostRemoveReq struct {
	Codes []string `json:"codes"`
}

type PostSaveReq struct {
	Code     string `json:"code"`
	PostName string `json:"postName"`
	OrderNum int32  `json:"orderNum"`
	Status   int32  `json:"status,optional"`
}

type PostStatusReq struct {
	Code   string `json:"code"`
	Status int32  `json:"status"`
}

type PostUpdateReq struct {
	Id       int64  `json:"id"`
	Code     string `json:"code"`
	PostName string `json:"postName"`
	OrderNum int32  `json:"orderNum"`
	Status   int32  `json:"status,optional"`
}

type RoleDetail struct {
	Id         string `json:"id"`
	Code       string `json:"code"`
	RoleName   string `json:"roleName"`
	RoleSort   int32  `json:"roleSort"`
	Status     int32  `json:"status"`
	CreateTime string `json:"createTime"`
}

type RolePageReq struct {
	Current  int    `form:"current,default=1"`
	Size     int    `form:"size,default=10"`
	RoleName string `form:"roleName,optional"`
	Status   int32  `form:"status,optional"`
}

type RolePageResp struct {
	Total   int64        `json:"total"`
	Records []RoleDetail `json:"records"`
	Size    int          `json:"size"`
	Current int          `json:"current"`
	Pages   int          `json:"pages"`
}

type RoleRemoveReq struct {
	Ids []string `json:"ids"`
}

type RoleSubmitReq struct {
	Id       string `json:"id,optional"`
	Code     string `json:"code"`
	RoleName string `json:"roleName"`
	OrderNum int32  `json:"orderNum"`
	Status   int32  `json:"status,optional"`
	Remark   string `json:"remark,optional"`
}

type RoleUpdateStatusReq struct {
	Id     string `json:"id"`
	Status int32  `json:"status"`
}

type UserDetail struct {
	Id         string   `json:"id"`
	Code       string   `json:"code"`
	Username   string   `json:"username"`
	RealName   string   `json:"realName"`
	Phone      string   `json:"phone"`
	Email      string   `json:"email"`
	Sex        int32    `json:"sex"`
	DeptId     string   `json:"deptId"`
	DeptName   string   `json:"deptName"`
	Status     int32    `json:"status"`
	Avatar     string   `json:"avatar"`
	RoleCodes  []string `json:"roleCodes"`
	CreateTime string   `json:"createTime"`
}

type UserEntity struct {
	UserCode string `json:"userCode"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	User  UserEntity `json:"user"`
	Roles []string   `json:"roles"`
	Perms []string   `json:"perms"`
}

type UserListReq struct {
	Username string `form:"username,optional"`
	RealName string `form:"realName,optional"`
	Phone    string `form:"phone,optional"`
	Status   int32  `form:"status,optional"`
	DeptCode string `form:"deptCode,optional"`
}

type UserListResp struct {
	List []UserDetail `json:"list"`
}

type UserRemoveReq struct {
	Ids []string `json:"ids"`
}

type UserResetPasswordReq struct {
	Id string `json:"id"`
}

type UserSubmitReq struct {
	Id       string `json:"id,optional"`
	Code     string `json:"code,optional"`
	NickName string `json:"nickName"`
	RealName string `json:"realName"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	DeptCode string `json:"deptCode"`
	Sex      int32  `json:"sex,optional"`
	Status   int32  `json:"status,optional"`
}

type UserUpdateStatusReq struct {
	Id     string `json:"id"`
	Status int32  `json:"status"`
}
